[package]
name = "tabled-typeclass-resolution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpds = "0.13.0"
smol_str = "0.2.0"
